### PR TITLE
Replace hardcoded localization paths with CleanerML-entries

### PR DESCRIPTION
**Pull request by tstenner**
This is the same as the last pull request but based on the current master so there's no merge conflict

### CODE REVIEW

**Comment by az0** [comment]
@tstenner   This looks interesting and I would like to take a closer look.  I did notice that the Travis CI build failed.  Please see https://travis-ci.org/az0/bleachbit/jobs/55505346#L1438

**Comment by tstenner** [comment]
The test passes on my machine, I'm assuming that the VMs has linked /usr/share/locale somewhere else. After removing the check if the path starts with `/usr/share/locale` everything passes.

**Comment by tstenner** [comment]
I noticed that directories aren't deleted recursively at the moment. What would be the best way to implement this (e.g. as flag to `Delete(path,recurse=True)`)?

**Comment by az0** [comment]
To delete recursively, try something like "for f in FileUtilities.children_in_directories(path, True): delete(path)" to iterate through all the children in a directory.  Then remember to delete the parent.

**Comment by tstenner** [comment]
Thanks for your suggestion, I already implemented it and it's working on my machine (still waiting for Travis).

**Comment by az0** [comment]
Travis CI looks OK (except for an apparently-unrelated network error).  Please allow some patience for me to look more at the whole thing.  Thank you.

**Comment by az0** [comment]
Released in BleachBit 1.7.7 beta.  Please test:
http://bleachbit.sourceforge.net/news/bleachbit-177-beta

**Pull request merged**
