### PR TITLE
Rename to Winapp2.py

### PR DESCRIPTION
**Pull request by ROCKNROLLKID**
Rename this to Winapp2.py because Winapp is a official file from Piriform that is copyrighted. To avoid any legal misunderstanding, and because the actual file name we use is the community made file, Winapp2, we should call this file Winapp2.py.

### CODE REVIEW

**Comment by az0** [comment]
File names cannot be copyrighted, and the [legal misunderstanding was resolved in 2003](https://www.bleachbit.org/news/winapp2ini-issue-piriform-resolved). 

Still, I would accept this change just to be consistent with the filename Winapp2.ini, but there are merge conflicts. Please take a look. Thanks!

**Comment by ROCKNROLLKID** [comment]
I am sorry, but I am still kind of noobish to GitHub, how do I view merge conflicts? When I try to click Resolve conflicts, it says that this "is too complex for web editor".

**Comment by az0** [comment]
One option is starting over

On December 26, 2016, at 1:41 PM, Alex <notifications@github.com> wrote:

I am sorry, but I am still kind of noobish to GitHub, how do I view merge conflicts? When I try to click Resolve conflicts, it says that this "is too complex for web editor".

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/az0/bleachbit","title":"az0/bleachbit","subtitle":"GitHub repository","main_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png">https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png</a>","avatar_image_url":"<a href="https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png">https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/az0/bleachbit">https://github.com/az0/bleachbit</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ROCKNROLLKID in #158: I am sorry, but I am still kind of noobish to GitHub, how do I view merge conflicts? When I try to click Resolve conflicts, it says that this \"is too complex for web editor\"."}],"action":{"name":"View Pull Request","url":"<a href="https://github.com/az0/bleachbit/pull/158#issuecomment-269240481">https://github.com/az0/bleachbit/pull/158#issuecomment-269240481</a>"}}}

**Comment by ROCKNROLLKID** [comment]
I will close this for now and re-open it when you are done with editing Winapp.py with your other PRs. When I forked this, no merge conflicts showed up, but with a 3 day old fork, so I think it is something code wise that caused this issue.

**Comment by az0** [comment]
The Python 3 change touched many parts of many files.

**Pull request closed without merging**
