### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by ekaris**
Upgrade to HTTPS links

### CODE REVIEW

**Comment by ROCKNROLLKID** [comment]
@az0 Also add https to the link in the description of the respo. Where it says "BleachBit system cleaner for Windows and Linux http://www.bleachbit.org" Should be https.

**Comment by az0** [comment]
OK, I changed it

**Comment by ROCKNROLLKID** [comment]
You missed the one in the description of the respo. The one on the code page on the top.

**Comment by az0** [comment]
Thank you for bringing this up, ekaris and ROCKNROLLKID. I really do appreciate HTTPS too. I will fix the repo description too.

**Pull request closed without merging**
