### PR TITLE
Rename Xchat to Hexchat

### PR DESCRIPTION
**Pull request by ROCKNROLLKID**
Fixes https://github.com/az0/bleachbit/pull/68

### CODE REVIEW

**Comment by az0** [comment]
I am not sure I asked before. Do you have a preferred name for the merge commit in Git and the release notes on bleachbit.org?

**Comment by ROCKNROLLKID** [comment]
You can just use ROCKNROLLKID. It is my forum name for all forums I go to.

**Comment by az0** [comment]
How about renaming the filename?

**Comment by ROCKNROLLKID** [comment]
Done.

**Pull request merged**
